src/Entity/Outing.php
<?php

namespace App\Entity;

use App\Repository\OutingRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinTable;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass = OutingRepository::class)
 *
 * @author Marin Taverniers
 */
class Outing {

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type = "integer")
     */
    private $id;

    /**
     * @ORM\Column(type = "string", length = 50)
     * @Assert\NotBlank(message = "The name is required.")
     * @Assert\Length(
     *      max = 50,
     *      maxMessage = "The name is too long (maximum {{ limit }} characters)."
     * )
     * @Assert\Regex(pattern = "/^[-' \w\p{L}]*$/u", message = "The name contains illegal characters.")
     */
    private $name;

    /**
     * @ORM\Column(type = "string", length = 1000)
     * @Assert\NotBlank(message = "The description is required.")
     * @Assert\Length(
     *      min = 5,
     *      max = 1000,
     *      minMessage = "The description is too short (minimum {{ limit }} characters).",
     *      maxMessage = "The description is too long (maximum {{ limit }} characters)."
     * )
     */
    private $description;

    // TODO: @Assert\DateTime(message = "The date is not a valid date.")
    /**
     * @ORM\Column(type = "datetime")
     * @Assert\NotBlank(message = "The date is required.")
     * @Assert\Range(
     *      invalidDateTimeMessage = "The date is not a valid date.",
     *      min = "now + 1 day",
     *      max = "now + 2 years",
     *      notInRangeMessage = "The date is not between tomorrow and the next 2 years.",
     * )
     */
    private $date;

    /**
     * @ORM\Column(type = "integer")
     * @Assert\NotBlank(message = "The duration is required.")
     * @Assert\Type(type = "int", message = "The duration is not a valid number.")
     * @Assert\Range(
     *      min = 15,
     *      max = 10080,
     *      notInRangeMessage = "The duration is not between {{ min }} and {{ max }}."
     * )
     */
    private $duration;

    // TODO: @Assert\Date(message = "The registration closing date is not a valid date.")
    /**
     * @ORM\Column(type = "date")
     * @Assert\NotBlank(message = "The registration closing date is required.")
     * @Assert\Range(
     *      invalidDateTimeMessage = "The registration closing date is not a valid date.",
     *      min = "now + 1 day",
     *      maxPropertyPath = "date",
     *      notInRangeMessage = "The registration closing date is not between tomorrow and the outing date.",
     * )
     */
    private $registrationClosingDate;

    /**
     * @ORM\Column(type = "integer")
     * @Assert\NotBlank(message = "The maximum registrants number is required.")
     * @Assert\Type(type = "int", message = "The maximum registrants number is not a valid number.")
     * @Assert\Range(
     *      min = 1,
     *      max = 10000,
     *      notInRangeMessage = "The maximum registrants number is not between {{ min }} and {{ max }}."
     * )
     */
    private $maxRegistrants;

    /**
     * @ORM\Column(type = "string", length = 1000, nullable = true)
     * @Assert\Length(
     *      min = 5,
     *      max = 1000,
     *      minMessage = "The cancellation reason is too short (minimum {{ limit }} characters).",
     *      maxMessage = "The cancellation reason is too long (maximum {{ limit }} characters)."
     * )
     */
    private $cancellationReason;

    /**
     * @ORM\ManyToOne(targetEntity = User::class, inversedBy = "organizedOutings")
     * @ORM\JoinColumn(nullable = false)
     */
    private $organizer;

    /**
     * @ORM\ManyToOne(targetEntity = Campus::class, inversedBy = "outings")
     * @ORM\JoinColumn(nullable = false)
     */
    private $campus;

    /**
     * @ORM\ManyToOne(targetEntity = Location::class, inversedBy = "outings")
     * @ORM\JoinColumn(nullable = false)
     * // Validates the embed location form in the outing creation form
     * @Assert\Valid()
     */
    private $location;

    /**
     * @ORM\ManyToOne(targetEntity = OutingState::class, inversedBy = "outings")
     * @ORM\JoinColumn(nullable = false)
     */
    private $state;

    /**
     * @ORM\ManyToMany(targetEntity = User::class, inversedBy = "outings")
     * @JoinTable(name = "outings_registrants")
     */
    private $registrants;

    public function __construct() {
        $this->registrants = new ArrayCollection();
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getName(): ?string {
        return $this->name;
    }

    public function setName(string $name): self {
        $this->name = $name;
        return $this;
    }

    public function getDescription(): ?string {
        return $this->description;
    }

    public function setDescription(string $description): self {
        $this->description = $description;
        return $this;
    }

    public function getDate(): ?DateTimeInterface {
        return $this->date;
    }

    public function setDate(?DateTimeInterface $date): self {
        $this->date = $date;
        return $this;
    }

    public function getDuration(): ?int {
        return $this->duration;
    }

    public function setDuration(int $duration): self {
        $this->duration = $duration;
        return $this;
    }

    public function getRegistrationClosingDate(): ?DateTimeInterface {
        return $this->registrationClosingDate;
    }

    public function setRegistrationClosingDate(?DateTimeInterface $registrationClosingDate): self {
        $this->registrationClosingDate = $registrationClosingDate;
        return $this;
    }

    public function getMaxRegistrants(): ?int {
        return $this->maxRegistrants;
    }

    public function setMaxRegistrants(int $maxRegistrants): self {
        $this->maxRegistrants = $maxRegistrants;
        return $this;
    }

    public function getCancellationReason(): ?string {
        return $this->cancellationReason;
    }

    public function setCancellationReason(?string $cancellationReason): self {
        $this->cancellationReason = $cancellationReason;
        return $this;
    }

    public function getOrganizer(): ?User {
        return $this->organizer;
    }

    public function setOrganizer(?UserInterface $organizer): self {
        $this->organizer = $organizer;
        return $this;
    }

    public function getCampus(): ?Campus {
        return $this->campus;
    }

    public function setCampus(?Campus $campus): self {
        $this->campus = $campus;
        return $this;
    }

    public function getLocation(): ?Location {
        return $this->location;
    }

    public function setLocation(?Location $location): self {
        $this->location = $location;
        return $this;
    }

    public function getState(): ?OutingState {
        return $this->state;
    }

    public function setState(?OutingState $state): self {
        $this->state = $state;
        return $this;
    }

    public function getRegistrants(): Collection {
        return $this->registrants;
    }

    public function addRegistrant(UserInterface $registrant): self {
        if (!$this->registrants->contains($registrant)) {
            $this->registrants[] = $registrant;
        }
        return $this;
    }

    public function removeRegistrant(UserInterface $registrant): self {
        $this->registrants->removeElement($registrant);
        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass = UserRepository::class)
 * @UniqueEntity("alias", message = "The alias is already used.")
 * @UniqueEntity("email", message = "The email is already used.")
 *
 * @author Marin Taverniers
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface {

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type = "integer")
     */
    private $id;

    /**
     * @ORM\Column(type = "string", length = 50, unique = true)
     * @Assert\NotBlank(message = "The username is required.")
     * @Assert\Length(
     *      min = 5,
     *      max = 50,
     *      minMessage = "The username is too short (minimum {{ limit }} characters).",
     *      maxMessage = "The username is too long (maximum {{ limit }} characters)."
     * )
     * @Assert\Regex(pattern = "/^[-\w]*$/", message = "The username contains illegal characters.")
     */
    private $alias;

    /**
     * @ORM\Column(type = "string", length = 50)
     * @Assert\NotBlank(message = "The last name is required.")
     * @Assert\Length(
     *      max = 50,
     *      maxMessage = "The last name is too long (maximum {{ limit }} characters)."
     * )
     * @Assert\Regex(pattern = "/^[-' a-zA-Z\p{L}]*$/u", message = "The last name contains illegal characters.")
     */
    private $lastName;

    /**
     * @ORM\Column(type = "string", length = 50)
     * @Assert\NotBlank(message = "The first name is required.")
     * @Assert\Length(
     *      max = 50,
     *      maxMessage = "The first name is too long (maximum {{ limit }} characters)."
     * )
     * @Assert\Regex(pattern = "/^[-' a-zA-Z\p{L}]*$/u", message = "The first name contains illegal characters.")
     */
    private $firstName;

    /**
     * @ORM\Column(type = "string", length = 250, unique = true)
     * @Assert\NotBlank(message = "The email is required.")
     * @Assert\Length(
     *      max = 250,
     *      maxMessage = "The email is too long (maximum {{ limit }} characters)."
     * )
     * @Assert\Email(message = "The email is not a valid email.")
     */
    private $email;

    /**
     * @ORM\Column(type = "string")
     */
    private $password;

    /**
     * @ORM\Column(type = "string", length = 15, nullable = true)
     * @Assert\Length(
     *      max = 15,
     *      maxMessage = "The phone number is too long (maximum {{ limit }} characters)."
     * )
     * @Assert\Regex(pattern = "/^\d*$/", message = "The phone number contains illegal characters.")
     */
    private $phone;

    /**
     * @ORM\Column(type = "string", length = 1000, nullable = true)
     * @Assert\Length(
     *      max = 1000,
     *      maxMessage = "The picture url is too long (maximum {{ limit }} characters)."
     * )
     * @Assert\Url(message = "The picture url is not a valid url.")
     */
    private $pictureUrl;

    /**
     * @ORM\Column(type = "json")
     */
    private $roles = [];

    // TODO: @Assert\Json(message = "The roles array is not a valid JSON object.")

    /**
     * @ORM\ManyToOne(targetEntity = Campus::class, inversedBy = "users")
     * @ORM\JoinColumn(nullable = false)
     */
    private $campus;

    /**
     * @ORM\OneToMany(targetEntity = Outing::class, mappedBy = "organizer")
     */
    private $organizedOutings;

    /**
     * @ORM\ManyToMany(targetEntity = Outing::class, mappedBy = "registrants")
     */
    private $outings;

    public function __construct() {
        $this->organizedOutings = new ArrayCollection();
        $this->outings = new ArrayCollection();
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getAlias(): ?string {
        return $this->alias;
    }

    public function setAlias(string $alias): self {
        $this->alias = $alias;
        return $this;
    }

    public function getLastName(): ?string {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self {
        $this->lastName = $lastName;
        return $this;
    }

    public function getFirstName(): ?string {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self {
        $this->firstName = $firstName;
        return $this;
    }

    public function getEmail(): ?string {
        return $this->email;
    }

    public function setEmail(string $email): self {
        $this->email = $email;
        return $this;
    }

    public function getPassword(): ?string {
        return $this->password;
    }

    public function setPassword(string $password): self {
        $this->password = $password;
        return $this;
    }

    public function getPhone(): ?string {
        return $this->phone;
    }

    public function setPhone(?string $phone): self {
        $this->phone = $phone;
        return $this;
    }

    public function getPictureUrl(): ?string {
        return $this->pictureUrl;
    }

    public function setPictureUrl(?string $pictureUrl): self {
        $this->pictureUrl = $pictureUrl;
        return $this;
    }

    public function getRoles(): array {
        $userRoles = $this->roles;
        if (!in_array("ROLE_USER_DISABLED", $userRoles)) {
            $userRoles[] = 'ROLE_USER';
        }
        return array_unique($this->roles);
    }

    public function setRoles(array $roles): self {
        $this->roles = $roles;
        return $this;
    }

    public function getCampus(): ?Campus {
        return $this->campus;
    }

    public function setCampus(?Campus $campus): self {
        $this->campus = $campus;
        return $this;
    }

    public function getOrganizedOutings(): Collection {
        return $this->organizedOutings;
    }

    public function addOrganizedOuting(Outing $organizedOuting): self {
        if (!$this->organizedOutings->contains($organizedOuting)) {
            $this->organizedOutings[] = $organizedOuting;
            $organizedOuting->setOrganizer($this);
        }
        return $this;
    }

    public function removeOrganizedOuting(Outing $organizedOuting): self {
        if ($this->organizedOutings->removeElement($organizedOuting)) {
            if ($organizedOuting->getOrganizer() === $this) {
                $organizedOuting->setOrganizer(null);
            }
        }
        return $this;
    }

    public function getOutings(): Collection {
        return $this->outings;
    }

    public function addOuting(Outing $registeredOuting): self {
        if (!$this->outings->contains($registeredOuting)) {
            $this->outings[] = $registeredOuting;
            $registeredOuting->addRegistrant($this);
        }
        return $this;
    }

    public function removeOuting(Outing $registeredOuting): self {
        if ($this->outings->removeElement($registeredOuting)) {
            $registeredOuting->removeRegistrant($this);
        }
        return $this;
    }

    public function getFullName(): string {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getShortName(): string {
        return $this->firstName . ' ' . substr($this->lastName, 0, 1) . '.';
    }

    /* Generated by "make:user" */

    /**
     * A visual identifier that represents this user.
     */
    public function getUserIdentifier(): string {
        return (string)$this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string {
        return $this->getUserIdentifier();
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm in your security.yaml.
     */
    public function getSalt(): ?string {
        return null;
    }

    public function eraseCredentials() {
        // If you store any temporary, sensitive data on the user, clear it here
    }
}

templates/outing/cancel.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Annulation de sortie | {{ parent() }}
{% endblock %}

{% block body %}
    <h1 class="h3">Annulation de sortie</h1>

    <fieldset>
        <legend>Informations</legend>
        <div class="row">
            <label for="name" class="col form-label text-secondary text-end">Nom</label>
            <span id="name" class="col form-label">{{ outing.name }}</span>
        </div>
        <div class="row">
            <label for="date" class="col form-label text-secondary text-end">Date</label>
            <span id="date" class="col form-label">{{ outing.date|date('d/m/Y - H:i') }}</span>
        </div>
        <div class="row">
            <label for="campus" class="col form-label text-secondary text-end">Campus</label>
            <span id="campus" class="col form-label">{{ outing.campus.name }}</span>
        </div>
        <div class="row">
            <label for="location" class="col form-label text-secondary text-end">Lieu</label>
            <span id="location" class="col form-label">{{ outing.location.name }}</span>
        </div>
        <div class="row">
            <label for="address" class="col form-label text-secondary text-end">Adresse</label>
            <span id="address" class="col form-label">
                {{ outing.location.street }} <br/>
                {{ outing.location.city.postalCode }} {{ outing.location.city.name }}
            </span>
        </div>
    </fieldset>

    {{ form_start(cancelForm) }}
    <fieldset>
        {{ form_errors(cancelForm) }}
        {{ form_widget(cancelForm) }}
    </fieldset>

    <div class="text-center">
        <div class="btn-group">
            <button type="submit" class="me-1 btn btn-sm btn-danger">Valider</button>
            {% include "fragment/home.html.twig" %}
        </div>
    </div>
    {{ form_end(cancelForm) }}
{% endblock %}

templates/outing/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Créer une sortie | {{ parent() }}
{% endblock %}

{% block body %}

    <h1>Créer une sortie</h1>

{% endblock %}

templates/outing/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ outing.name }} | {{ parent() }}
{% endblock %}

{% block body %}
    <h1 class="h3">{{ outing.name }}</h1>

    <fieldset>
        <legend>Informations</legend>
        <div class="row justify-content-center">
            <div class="col-5">
                <div class="row">
                    <label for="name" class="col form-label text-secondary text-end">Nom</label>
                    <span id="name" class="col form-label">{{ outing.name }}</span>
                </div>
                <div class="row">
                    <label for="date" class="col form-label text-secondary text-end">Date</label>
                    <span id="date" class="col form-label">{{ outing.date|date('d/m/Y - H:i') }}</span>
                </div>
                <div class="row">
                    <label for="closing-date" class="col form-label text-secondary text-end">
                        Fin des inscriptions
                    </label>
                    <span id="closing-date" class="col form-label">
                        {{ outing.registrationClosingDate|date('d/m/Y') }}
                    </span>
                </div>
                <div class="row">
                    <label for="duration" class="col form-label text-secondary text-end">Durée (minutes)</label>
                    <span id="duration" class="col form-label">{{ outing.duration }}</span>
                </div>
                <div class="row">
                    <label for="description" class="col form-label text-secondary text-end">Description</label>
                    <span id="description" class="col form-label">{{ outing.description }}</span>
                </div>
                <div class="row">
                    <label for="campus" class="col form-label text-secondary text-end">Campus</label>
                    <span id="campus" class="col form-label">{{ outing.campus.name }}</span>
                </div>
                <div class="row">
                    <label for="organizer" class="col form-label text-secondary text-end">Organisateur</label>
                    <span id="organizer" class="col form-label">{{ outing.organizer.fullName }}</span>
                </div>
            </div>

            <div class="col-5">
                <div class="row">
                    <label for="location" class="col form-label text-secondary text-end">Lieu</label>
                    <span id="location" class="col form-label">{{ outing.location.name }}</span>
                </div>
                <div class="row">
                    <label for="address" class="col form-label text-secondary text-end">Adresse</label>
                    <span id="address" class="col form-label">
                        {{ outing.location.street }} <br/>
                        {{ outing.location.city.postalCode }} {{ outing.location.city.name }}
                    </span>
                </div>
                <div class="row">
                    <label for="latitude" class="col form-label text-secondary text-end">Latitude</label>
                    <span id="latitude" class="col form-label">{{ outing.location.latitude }}</span>
                </div>
                <div class="row">
                    <label for="longitude" class="col form-label text-secondary text-end">Longitude</label>
                    <span id="longitude" class="col form-label">{{ outing.location.longitude }}</span>
                </div>
            </div>
        </div>
    </fieldset>

    <fieldset>
        <legend>État</legend>
        <div class="row">
            <label for="registrants" class="col form-label text-secondary text-end">Inscrits / Places</label>
            <span id="registrants" class="col form-label">
                {{ outing.registrants|length }} / {{ outing.maxRegistrants }}
            </span>
        </div>
        <div class="row">
            <label for="state" class="col form-label text-secondary text-end">État</label>
            <span id="state" class="col form-label">{{ outing.state.friendlyName }}</span>
        </div>
        {% if (outing.cancellationReason) %}
            <div class="row">
                <label for="cancellation-reason" class="col form-label text-secondary text-end">
                    Motif d'annulation
                </label>
                <span id="cancellation-reason" class="col form-label">{{ outing.cancellationReason }}</span>
            </div>
        {% endif %}
    </fieldset>

    <legend>Inscrits</legend>
    {% if (outing.registrants|length > 0) %}
        <div class="row justify-content-center">
            <div class="col-6">
                <table class="mb-3 table table-bordered table-striped table-secondary table-sm align-middle text-center">
                    <tr>
                        <th scope="col">Pseudo</th>
                        <th scope="col">Nom</th>
                    </tr>
                    {% for registrant in outing.registrants %}
                        <tr>
                            <td>
                                <a href="{{ path('user_detail', {id: registrant.id}) }}">{{ registrant.alias }}</a>
                            </td>
                            <td>{{ registrant.fullName }} </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    {% else %}
        <div class="alert alert-danger">
            Aucun inscrit n'a été trouvé.
        </div>
    {% endif %}

    <div class="text-center">
        <div class="btn-group">
            {% include "fragment/home.html.twig" %}
        </div>
    </div>
{% endblock %}

templates/outing/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Sorties | {{ parent() }}
{% endblock %}

{% block body %}
    <h1 class="h3">Sorties</h1>

    <div class="text-end">
        <h6>Date : {{ "now"|date("d/m/Y") }}</h6>
        <h6>Utilisateur : {{ app.user.fullName }}</h6>
    </div>

    <fieldset>
        <legend>Filtres</legend>
        {{ form_start(searchForm) }}
        {{ form_errors(searchForm) }}
        <div class="row align-items-center">
            <div class="col">
                {{ form_row(searchForm.campus) }}
                {{ form_row(searchForm.name) }}
                <div class="row">
                    <div class="col">
                        {{ form_row(searchForm.minDate) }}
                    </div>
                    <div class="col">
                        {{ form_row(searchForm.maxDate) }}
                    </div>
                </div>
            </div>
            <div class="col">
                {{ form_row(searchForm.isUserOrganizer) }}
                {{ form_row(searchForm.isUserRegistrant) }}
                {{ form_row(searchForm.isUserNotRegistrant) }}
                {{ form_row(searchForm.isFinished) }}
            </div>
        </div>

        <div class="text-end">
            <div class="btn-group">
                <button type="submit" class="btn btn-sm btn-secondary">Rechercher</button>
            </div>
        </div>
        {{ form_end(searchForm) }}
    </fieldset>

    <legend>Sorties</legend>
    {% if (outings) %}
        <table class="my-3 table table-bordered table-striped table-secondary table-sm align-middle text-center">
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">Date</th>
                <th scope="col">Fin des inscriptions</th>
                <th scope="col">Inscrits / Places</th>
                <th scope="col">État</th>
                <th scope="col">Inscrit</th>
                <th scope="col">Organisateur</th>
                <th scope="col">Actions</th>
            </tr>
            {% for outing in outings %}
                <tr>
                    <td>{{ outing.name }}</td>
                    <td>
                        {{ outing.date|date("d/m/Y") }}<br/>
                        {{ outing.date|date("H:i") }}
                    </td>
                    <td>{{ outing.registrationClosingDate|date("d/m/Y") }}</td>
                    <td>{{ outing.registrants|length }} / {{ outing.maxRegistrants }}</td>
                    <td>{{ outing.state.friendlyName }}</td>
                    <td>{{ app.user in outing.registrants ? "Oui" : "-" }}</td>
                    <td>
                        <a href="{{ path('user_detail', {id: outing.organizer.id}) }}">{{ outing.organizer.shortName }}</a>
                        {% if (app.user == outing.organizer) %}
                            <br/>
                            <span>(vous)</span>
                        {% endif %}
                    </td>
                    <td>
                        <div class="btn-group">
                            {% set isOutingPrivate = outingService.isOutingPrivate(outing) %}
                            {% set isOutingPublic = outingService.isOutingPublic(outing) %}
                            {% set isOutingOpenForRegistration = outingService.isOutingOpenForRegistration(outing) %}
                            {% set isOutingUpcoming = outingService.isOutingUpcoming(outing) %}
                            {% set isUserOrganizer = (app.user == outing.organizer) %}
                            {% set isUserRegistrant = (app.user in outing.registrants) %}

                            {% if ((isUserOrganizer) and (isOutingPrivate)) %}
                                <a href="{{ path('outing_edit', {id: outing.id}) }}"
                                   class="btn btn-sm btn-primary">
                                    Modifier
                                </a>
                                <a href="{{ path('outing_publish', {id: outing.id}) }}"
                                   class="ms-1 btn btn-sm btn-success">
                                    Publier
                                </a>
                            {% endif %}

                            {% if (isOutingPublic) %}
                                <a href="{{ path('outing_detail', {id: outing.id}) }}"
                                   class="btn btn-sm btn-secondary">
                                    Voir
                                </a>

                                {% if (((is_granted('ROLE_ADMIN')) or (isUserOrganizer)) and (isOutingUpcoming)) %}
                                    <a href="{{ path('outing_cancel', {id: outing.id}) }}"
                                       class="ms-1 btn btn-sm btn-danger">
                                        Annuler
                                    </a>
                                {% endif %}

                                {% if ((isOutingOpenForRegistration) and (not (isUserRegistrant))) %}
                                    <a href="{{ path('outing_register', {id: outing.id}) }}"
                                       class="ms-1 btn btn-sm btn-success">
                                        S'inscrire
                                    </a>
                                {% elseif ((isOutingUpcoming) and (isUserRegistrant)) %}
                                    <a href="{{ path('outing_unregister', {id: outing.id}) }}"
                                       class="ms-1 btn btn-sm btn-primary">
                                        Se désinscrire
                                    </a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <div class="alert alert-danger">
            Aucune sortie n'a été trouvée.
        </div>
    {% endif %}

    <div class="text-center">
        <div class="btn-group">
            <a href="{{ path('outing_create') }}" class="btn btn-sm btn-primary">Nouvelle sortie</a>
        </div>
    </div>
{% endblock %}